version: '3'

services:
  php:
    container_name: setup-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-network

  nginx:
    container_name: setup-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '${APP_PORT:-80}:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-network

  mysql:
    container_name: setup-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-network
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  setup-network:
    driver: bridge

volumes:
  setup-data:
    driver: local